# Generated by Django 5.1.7 on 2025-04-12 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_profile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Foto de Perfil'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('instructions', models.TextField(verbose_name='Instrucciones')),
                ('prep_time', models.PositiveIntegerField(default=0, verbose_name='Tiempo de Preparación (minutos)')),
                ('cook_time', models.PositiveIntegerField(default=0, verbose_name='Tiempo de Cocción (minutos)')),
                ('servings', models.PositiveIntegerField(default=1, verbose_name='Porciones')),
                ('difficulty', models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], default='MEDIA', max_length=10, verbose_name='Dificultad')),
                ('recipe_image', models.ImageField(blank=True, null=True, upload_to='recipe_pics/', verbose_name='Imagen de la Receta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('published', models.BooleanField(default=True, verbose_name='Publicada')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.category', verbose_name='Categoría')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.recipe', verbose_name='Receta'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
