# Generated by Django 5.1.7 on 2025-04-12 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_comment_post_alter_comment_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario del repost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reposteo')),
                ('original_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='post.recipe', verbose_name='Receta original')),
                ('reposted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposted_recipes', to=settings.AUTH_USER_MODEL, verbose_name='Reposteado por')),
            ],
            options={
                'verbose_name': 'Repost',
                'verbose_name_plural': 'Reposts',
                'unique_together': {('original_recipe', 'reposted_by')},
            },
        ),
    ]
